### ISSUE TITLE
Training error regarding retinanet

### ISSUE THREAD

**Issue by szation** [fizyr/keras-maskrcnn#113]
Hi, 

I installed keras-retinanet from git using the follwing command:
> pip install --user git+https://github.com/fizyr/keras-retinanet

And when I tried training on custom dataset as follows, I get the following error:
> ./keras_maskrcnn/bin/train.py csv [path/to/annotation.csv] [path/to/class.csv]

Could you please help what I have done wrong? I'm using tf=1.15 and keras=2.3.1.

Using TensorFlow backend.
Creating model, this may take a second...
WARNING:tensorflow:From /scl_nas/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /scl_nas/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Traceback (most recent call last):
  File "./keras_maskrcnn/bin/train.py", line 321, in <module>
    main()
  File "./keras_maskrcnn/bin/train.py", line 287, in main
    anchor_params=anchor_params
  File "./keras_maskrcnn/bin/train.py", line 60, in create_models
    anchor_params=anchor_params
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/resnet.py", line 30, in maskrcnn
    return resnet_maskrcnn(*args, backbone=self.backbone, **kwargs)
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/resnet.py", line 51, in resnet_maskrcnn
    model = retinanet.retinanet_mask(inputs=inputs, num_classes=num_classes, backbone_layers=resnet.outputs[1:], mask_dtype=mask_dtype, **kwargs)
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/retinanet.py", line 154, in retinanet_mask
    **kwargs
  File "/root/.local/lib/python3.7/site-packages/keras_retinanet/models/retinanet.py", line 307, in retinanet
    features = create_pyramid_features(backbone_layers, pyramid_levels)
  File "/root/.local/lib/python3.7/site-packages/keras_retinanet/models/retinanet.py", line 142, in __create_pyramid_features
    P5           = keras.layers.Conv2D(feature_size, kernel_size=1, strides=1, padding='same', name='C5_reduced')(backbone_layers['C5'])
TypeError: list indices must be integers or slices, not str

**Comment by szation** [comment]
Sorry to bother you.
I tried with older version of keras-retinanet and keras-maskrcnn train.py seems working.

**Comment by imransalam** [comment]
@szation which versions?
