### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by devansdev** [fizyr/keras-maskrcnn#40]
OM when allocating tensor with shape[100,256,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

Traceback (most recent call last):
  File "keras_maskrcnn/bin/train.py", line 314, in <module>
    main()
  File "keras_maskrcnn/bin/train.py", line 310, in main
    max_queue_size=1,
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/home/devinda/libs/keras-maskrcnn/.env/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[100,256,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/gradients/mask_submodel/roi_mask_features/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](mask_submodel/roi_mask_upsample/resize_images/ResizeNearestNeighbor, PermConstNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by hgaiser** [comment]
Two questions, what GPU are you using, and are you sure you're on the latest version of maskrcnn? There was a change not so long ago that greatly reduces the memory requirements.

**Comment by devansdev** [comment]
1. GeForce 940M, is this not enough?
2. I will get an update

**Comment by hgaiser** [comment]
It only has 2Gb of memory, which isn't enough. The default settings on my system uses 8531Mb when training COCO.

**Comment by devansdev** [comment]
it has 4GB, aslo i'm not training COCO but my own dataset, still conditions same? need 8.5 GB?

**Comment by devansdev** [comment]
I got an update and its working, Thanks
