### ISSUE TITLE
Tensor shape error while training starts

### ISSUE THREAD

**Issue by amardeepjaiman** [fizyr/keras-maskrcnn#63]
I am getting following error while startring the training. I have created my custom dataset in coco format with 1000x1000 training image size.

Total params: 39,333,614
Trainable params: 39,227,374
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
/anaconda/envs/maskrcnn_retinanet/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/50
Traceback (most recent call last):
  File "keras_maskrcnn/bin/train.py", line 313, in <module>
    main()
  File "keras_maskrcnn/bin/train.py", line 309, in main
    max_queue_size=1,
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/anaconda/envs/maskrcnn_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/anaconda/envs/maskrcnn_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 78400 values, but the requested shape requires a multiple of 300
         [[{{node masks/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](mask_submodel/roi_mask/Sigmoid-2-0-TransposeNCHWToNHWC-LayoutOptimizer, masks/Reshape/shape)]]
         [[{{node loss/add_1/_2619}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_12418_loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Please let me know, what could be the issue.

**Comment by hgaiser** [comment]
Sorry for the delay, we've been quite busy lately. Is this still an issue for you? If so, could you share a single image and the corresponding COCO style dataset file? I could maybe have a look sometime to see what the problem is.

**Comment by amardeepjaiman** [comment]
yes I am still facing the issue. I am having around 40k training images of size 500x500. Dataset is in coco format. Do i have to resize the images to any specific size ? what is the acceptable input size to the network ?

**Comment by hgaiser** [comment]
The network should accept any input size. There are some lower limits (I believe 224x224) and some upper limit but that is restricted by your hardware. I meant if you can share a minimal example of a dataset that produces this error, it gives me something to experiment with.

**Comment by amardeepjaiman** [comment]
Thanks @hgaiser . My dataset is in coco format. as a subset can i provide you the image and corresponding masks ?

**Comment by amardeepjaiman** [comment]
Hi @hgaiser , would you like to take a look at the dataset to figure out whats happening with the dataset. I know its something with the dataset or generator. could you guide me what specific should i look for in data or any debugging steps. i have used debug.py to view the annotations and anchors but it seems fine.

Any help is appreciated.

Thanks in advance

**Comment by hgaiser** [comment]
Hey @amardeepjaiman . Yes if you can share a minimal dataset somewhere with this issue, then I can have a look.

**Comment by amardeepjaiman** [comment]
Hi @hgaiser , I have uploaded a sample dataset on following location. Please have a look.

https://www.dropbox.com/s/2o4364568bf7vj2/sample_dataset.zip?dl=0

**Comment by hgaiser** [comment]
Do you happen to have the annotations as well? These are just the images and the masks, correct?

**Comment by amardeepjaiman** [comment]
yes, but i have annotations for full dataset in coco format. do you want me provide annotaion for sample too. I can generate and provide to you.

**Comment by hgaiser** [comment]
Yes, the smaller the dataset the better.

**Comment by amardeepjaiman** [comment]
ok. Please access this zip file for small dataset with coco annotations.

https://www.dropbox.com/s/ijzz9ippm8mjvvy/sample_dataset_with_anno%28coco%29.zip?dl=0

**Comment by amardeepjaiman** [comment]
hey @hgaiser , did you get a chance to look at the dataset ?

**Comment by hgaiser** [comment]
I just trained a while on the training set (had to move some files around to different dirs to get it to accept the dataset). What version of tensorflow are you running?

**Comment by amardeepjaiman** [comment]
I have tried running it on different version of tensorflow like 1.10 and currently 1.13. Any pointers what could be wrong with the dataset ? or whats your observation ?

**Comment by amardeepjaiman** [comment]
@hgaiser , any update on this issue ?

**Comment by hgaiser** [comment]
I don't know, as I said the dataset seems to be training fine for me. Would you like me to re-upload your modified dataset and give you the command I used for training?

**Comment by amardeepjaiman** [comment]
that would be great  i guess. could you please highlight the modification you did. and also the training command.

also do you have any DockerFile of this environment you are using. So that i can replicate this here?

**Comment by amardeepjaiman** [comment]
Hi @hgaiser ,

any update ?Did you upload the dataset somewhere ? 

Thanks,
Amardeep

**Comment by hgaiser** [comment]
```shell
python keras_maskrcnn/bin/train.py --weights snapshots/resnet50_coco_v0.2.0.h5 --no-evaluation coco ~/crash_dataset/train
```

The modifications I made were just moving some files around so that `train.py` knew how to parse it as a generator.

[crash_dataset.zip](https://github.com/fizyr/keras-maskrcnn/files/3093907/crash_dataset.zip)

**Comment by amardeepjaiman** [comment]
Thanks @hgaiser . I will try this. is there any specific tensorflow version installed on your environment ?

**Comment by hgaiser** [comment]
We're using 1.13.

**Comment by amardeepjaiman** [comment]
Hi @hgaiser , I have narrowed down the problem now. If i use the --batch-size argument then only my problem occurs. If i leave to default i.e. 1, then problem dont occur.

python keras_maskrcnn/bin/train.py --weights snapshots/resnet50_coco_v0.2.0.h5 --batch-size=2 --no-evaluation coco ~/crash_dataset/train

its giving same error. Could you please check ? However I have started the training without giving batch size.

**Comment by hgaiser** [comment]
Hmm interesting. I can't check it right now but hopefully I can check this
soon.

**Comment by hgaiser** [comment]
I just ran the same command, but with `--batch-size 2`:

```shell
python keras_maskrcnn/bin/train.py --weights snapshots/resnet50_coco_v0.2.0.h5 --no-evaluation --batch-size 2 coco ~/crash_dataset/train
```

It didn't crash for me. Is this also what you ran?

**Comment by amardeepjaiman** [comment]
yes. Giving batch size crashing for me.

**Comment by hgaiser** [comment]
Then I've run out of ideas for things to test =\

**Comment by pappuyadav** [comment]
> Hi @hgaiser , I have narrowed down the problem now. If i use the --batch-size argument then only my problem occurs. If i leave to default i.e. 1, then problem dont occur.
> 
> python keras_maskrcnn/bin/train.py --weights snapshots/resnet50_coco_v0.2.0.h5 --batch-size=2 --no-evaluation coco ~/crash_dataset/train
> 
> its giving same error. Could you please check ? However I have started the training without giving batch size.

@amardeepjaiman not sure if this might be the problem but please make sure you are not using "=" sign after "--batch-size" and rather a space before "2".
