### ISSUE TITLE
when i run ResNet50MaskRCNN.ipynb

### ISSUE THREAD

**Issue by zhangbo2008** [fizyr/keras-maskrcnn#71]
Using TensorFlow backend.
..\snapshots\resnet50_coco_v0.2.0.h5
2019-03-01 11:56:29.672404: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/ALL_PROJECT/python_project/keras-maskrcnn-master/examples/ResNet50MaskRCNN.py", line 77, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')
  File "..\keras_maskrcnn\models\__init__.py", line 59, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "C:\venv\lib\site-packages\keras\models.py", line 232, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\venv\lib\site-packages\keras\models.py", line 293, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\venv\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\venv\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\venv\lib\site-packages\keras\engine\topology.py", line 2361, in from_config
    process_layer(layer_data)
  File "C:\venv\lib\site-packages\keras\engine\topology.py", line 2330, in process_layer
    custom_objects=custom_objects)
  File "C:\venv\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\venv\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\venv\lib\site-packages\keras\engine\topology.py", line 2361, in from_config
    process_layer(layer_data)
  File "C:\venv\lib\site-packages\keras\engine\topology.py", line 2356, in process_layer
    layer(input_tensors[0], **kwargs)
  File "C:\venv\lib\site-packages\keras\engine\topology.py", line 545, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\venv\lib\site-packages\keras\layers\core.py", line 402, in call
    target_shape = self.compute_output_shape(input_shape)[1:]
  File "C:\venv\lib\site-packages\keras\layers\core.py", line 385, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "C:\venv\lib\site-packages\keras\layers\core.py", line 373, in _fix_unknown_dimension
    original = np.prod(input_shape, dtype=int)
  File "C:\venv\lib\site-packages\numpy\core\fromnumeric.py", line 2772, in prod
    initial=initial)
  File "C:\venv\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by hgaiser** [comment]
That's a strange error, never seen that before. What version of tensorflow are you using?

**Comment by zhangbo2008** [comment]
1.12

**Comment by hgaiser** [comment]
Can you describe in a bit more detail what steps you took?
