### ISSUE TITLE
error during training: bounding box resize

### ISSUE THREAD

**Issue by tinalegre** [fizyr/keras-maskrcnn#78]
It looks that for a given training sample, there were some issues with the bounding boxes. As it's difficult to find out which exact sample generated the error, I was wondering where the exact problem could be. Is it maybe an issue of a wrong annotated b-box? Here the error:

> epoch 00024: saving model to ./snapshots/resnet50_csv_24.h5
> Traceback (most recent call last):
>   File "./keras_maskrcnn/bin/train.py", line 327, in <module>
>     main()
>   File "./keras_maskrcnn/bin/train.py", line 323, in main
>     max_queue_size=args.max_queue_size
>   File "/home/user/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/user/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/home/user/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
>     callbacks.on_epoch_end(epoch, epoch_logs)
>   File "/home/user/.local/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/user/.local/lib/python3.6/site-packages/keras_retinanet/callbacks/common.py", line 31, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/callbacks/eval.py", line 66, in on_epoch_end
    save_path=self.save_path
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/utils/eval.py", line 212, in evaluate
    mask = cv2.resize(mask, (box[2] - box[0], box[3] - box[1]))
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3785: error: (-215:Assertion failed) !dsize.empty() || (inv_scale_x > 0 && inv_scale_y > 0) in function 'resize'`

Also after 23, I'm getting the following accuracy:
`Epoch 00023: saving model to ./snapshots/resnet50_csv_23.h5
247 instances of class classA with average precision: 0.0178
86 instances of class classB with average precision: 0.0423
mAP: 0.0300`

Are those values normal during training? I was expecting to see a higher mAP after 23 iterations, considering that I'm using a pretrained model:
`python3 ./keras_maskrcnn/bin/train.py --weights=./weights/resnet50_coco_best_v2.1.0.h5 --gpu=0 --epochs=100 --steps=500 --config=keras_maskrcnn/config/config.ini csv /annotations4model/tain_set.csv /annotations4model/class_mapping.txt --val-annotations /annotations4model/valid_set.csv`

**Comment by hgaiser** [comment]
It seems like one of your detections is causing an error. Could you print `box` in [this](https://github.com/fizyr/keras-maskrcnn/blob/master/keras_maskrcnn/utils/eval.py#L212) line to inspect the values of the boxes that are detected? We should filter for incorrect box detections, but it seems by the look of your error that it didn't happen here.

**Comment by amardeepjaiman** [comment]
I am getting the same error

File "./keras_maskrcnn/bin/../../keras_maskrcnn/utils/eval.py", line 212, in evaluate
mask = cv2.resize(mask, (box[2] - box[0], box[3] - box[1]))
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3785: error: (-215:Assertion failed) !dsize.empty() || (inv_scale_x > 0 && inv_scale_y > 0) in function 'resize'`

after 7 epochs of training. What could be the issue ?

**Comment by hgaiser** [comment]
@amardeepjaiman could you print `box` as mentioned earlier?

**Comment by amardeepjaiman** [comment]
Yes i have printed the box values. Please check the output below :

[  0  55  96 107]
[430 185  65  89]
[394 255  67  66]
[229   0 116  90]
[442 162  57  91]
[ 21 480  64  18]
[  0 302 131 149]
[350 313  67  86]
[319 305  60  80]
[421 213  67  73]
[289 468  53  29]
[ 12  57 469 442]
[463 161  36  72]
[236   0  60  25]
[369 254  90 101]
[236   0 100  32]
[328 269 118 127]
[426 302  20  23]
[100 231  29  22]
[225  20  79  71]
[  0 312  25  55]
[100 489  23   9]
[406 497  37   1]
[410 497  36   0]
Traceback (most recent call last):
  File "keras_maskrcnn/bin/train.py", line 329, in <module>
    main()
  File "keras_maskrcnn/bin/train.py", line 325, in main
    max_queue_size=args.max_queue_size
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/amjn_cowi/.local/lib/python3.6/site-packages/keras_retinanet/callbacks/common.py", line 31, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "keras_maskrcnn/bin/../../keras_maskrcnn/callbacks/coco.py", line 44, in on_epoch_end
    coco_eval_stats = evaluate_coco(self.generator, self.model, self.threshold)
  File "keras_maskrcnn/bin/../../keras_maskrcnn/utils/coco_eval.py", line 62, in evaluate_coco
    mask = cv2.resize(mask[:, :, label], (b[2], b[3]))
cv2.error: OpenCV(4.0.1) /io/opencv/modules/imgproc/src/resize.cpp:3787: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'

**Comment by RohitMidha23** [comment]
@amardeepjaiman were you able to figure out what went worng? I have the same issue :/
