### ISSUE TITLE
Syntax error while running train.py

### ISSUE THREAD

**Issue by abhaysjuneja** [fizyr/keras-maskrcnn#8]
```python
$ ./keras_maskrcnn/bin/train.py coco ~/Downloads/train2017/
/home/ros/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "./keras_maskrcnn/bin/train.py", line 288, in <module>
    main()
  File "./keras_maskrcnn/bin/train.py", line 235, in main
    backbone = models.backbone(args.backbone)
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/__init__.py", line 33, in backbone
    from .resnet import ResNetBackbone as b
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/resnet.py", line 23, in <module>
    from ..models import retinanet, Backbone
  File "./keras_maskrcnn/bin/../../keras_maskrcnn/models/retinanet.py", line 32
    **options,
             ^
SyntaxError: invalid syntax
```

**Comment by hgaiser** [comment]
Apparently that's not allowed in python2. I'm assuming that's what you're using? You might run into other issues, but I fixed this one at least.

13b1f8bb7d2a0745d58135644cb8b66aa80f1711
